services:
  ragebait-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres:5432/ragebait
      - DB_USERNAME=ragebait
      - DB_PASSWORD=password
      - DB_DRIVER=org.postgresql.Driver
      - DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - GEMINI_CREDENTIALS_JSON=file:/app/secrets/service-account.json
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/credentials/ragebait-458813-b014bfd11774.json:/app/secrets/service-account.json

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ragebait
      - POSTGRES_USER=ragebait
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
